# Generated by Django 5.2.4 on 2025-09-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='description',
            field=models.CharField(default='A brief description of the poll question', max_length=30),
        ),
    ]
