# Generated by Django 5.2.4 on 2025-09-26 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_user_rename_question_poll_volting_types_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='volting_types',
            new_name='voting_type',
        ),
    ]
